CREATE database Train;
use Train;
CREATE TABLE Train_details(name varchar(40),Starting_point varchar(40),Destination_point varchar(40),Departure_time date,Takeoff Time,credited_at timestamp,Train_number bigint,noof_Bhogies int ); 
SELECT *FROM Train_details ;
INSERT Train_details VALUES('HampiExpress','Banglore','Hubli',current_date(),current_time(),now(),23457,34);
SELECT *FROM Train_details ;
INSERT Train_details VALUES('RanichannammaExpress','Mysore','Belgavi',current_date(),current_time(),now(),56789,45);
SELECT *FROM Train_details ;
INSERT Train_details VALUES('NandedhaExpress','Bangolre','Puna',current_date(),current_time(),now(),25678,56);
SELECT *FROM Train_details ;
INSERT Train_details VALUES('UdyanExpress','Banglore','Mumbai',current_date(),current_time(),now(),67854,43);
SELECT *FROM Train_details ;
INSERT Train_details VALUES('GoalGumbazaExpress','Banglore','Bijapur',current_date(),current_time(),now(),34562,44);
SELECT *FROM Train_details ;
INSERT Train_details VALUES('MysoreExpress','Mysore','Dharwad',current_date(),current_time(),now(),67435,24);
SELECT *FROM Train_details ;
INSERT Train_details VALUES('RajdhaniExpress','Hydrabad','Dehli',current_date(),current_time(),now(),32456,14);
SELECT *FROM Train_details ;
INSERT Train_details VALUES('ShatabdhiExpress','Banglore','Gulbarga',current_date(),current_time(),now(),456732,24);
SELECT *FROM Train_details ;
INSERT Train_details VALUES('GorakpurExpress','Gorakhapur','Banglore',current_date(),current_time(),now(),67453,84);
SELECT *FROM Train_details ;
INSERT Train_details VALUES('GomtiExpress','Dehli','Lucknow',current_date(),current_time(),now(),56423,32);
SELECT *FROM Train_details ;
